### ISSUE TITLE
-o flag not working

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte-upgrade#2]
`$ svelte-upgrade v2 test.html -o test.v2.html`

I am being asked whether I want to overwrite `test.html` (and if I agree, it actually does overwrite it).

**Comment by Conduitry** [comment]
afaict the problem is that it just plain old wasn't implemented in https://github.com/sveltejs/svelte-upgrade/blob/master/src/cli.js

**Comment by Rich-Harris** [comment]
d'oh. fixed
