### ISSUE TITLE
has a problem with less style blocks

### ISSUE THREAD

**Issue by gka** [sveltejs/svelte-upgrade#8]
can svelte-upgrade just ignore `<style>` blocks with a custom `lang` attribute?

as of now it's throwing an error bc it thinks the CSS is broken

```
Error transforming src/describe/App.html:
Identifier is expected
350:         vertical-align: top;
351:         margin-right: 1ex;
352:         .sort-menu li a .fa {
             ^
353:             opacity: 0.5;
354:             &:hover {
Wrote 1 file
Done in 2.23s.
```

**Comment by arxpoetica** [comment]
Likewise, it hates on sass / postcss:

```✔ Overwrite 14 files? … yes
Error transforming routes/_components/_repos/_repos.html:
Unexpected input
31:   .repo {
32:     padding: 20px;
33:     background-color: $dark-yellow;
                          ^
34:     box-shadow: 0 1px 10px #0e0e0e;
35:   }```

**Comment by arxpoetica** [comment]
@Rich-Harris wouldn't the better choice be to ignore CSS altogether in the update? Or is a change going on there too?

**Comment by arxpoetica** [comment]
For anyone else who encounters this, an annoying, but quicker fix is to just temporarily comment out any style tags:

```
<!-- <style>
	.repos {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
		grid-template-rows: auto;
		grid-gap: 20px;
		margin: 0 0 50px;
	}
...
</style> -->
```

And then the parser doesn't complain. You can then uncomment them after it runs.

**Comment by Rich-Harris** [comment]
> Or is a change going on there too?

No changes, no. As you suggest, the straightforward fix is to blank out the contents of `<style>` tags before parsing, so I've done that in https://github.com/sveltejs/svelte-upgrade/commit/f7ad837c33150cc3a8ec648167db753dbdf9bce3.

@gka if you successfully upgraded any of your components already, you'll probably want to unstage those changes before running 1.0.15, as svelte-upgrade isn't idempotent

**Comment by gka** [comment]
@Rich-Harris what does that mean? I did upgrade _all_ my components and set the svelte parser option to `v2` and it seems to be working nicely. what does idempotent mean?

If you mean running the script twice, that's not needed as I also "fixed" this already by commenting out all my LESS blocks. just opened this issue so other devs don't have to go through this in the future ;-)

**Comment by Rich-Harris** [comment]
Ah, gotcha 😀 Yeah, I just meant that if you'd run it on some components, and some had failed, and then you tried to run it again then it would probably barf on the components that had previously upgraded successfully. Idempotent just means that `f(x) === f(f(x))`
