### ISSUE TITLE
Computed properties: first character of prop omitted

### ISSUE THREAD

**Issue by nolanlawson** [sveltejs/svelte-upgrade#9]
Repro:

```bash
wget https://raw.githubusercontent.com/nolanlawson/pinafore/b72ed87/routes/_components/status/Status.html
svelte-upgrade v2 Status.html
```

Input (line 179):

```js
originalStatus: (status) => status.reblog ? status.reblog : status,
```

Output:

```js
originalStatus: (({ tatus) }) => status.reblog ? status.reblog : status,
```

Note it has `tatus` instead of `status`. Other computed properties are similarly truncated:

```js
originalStatus: (({ tatus) }) => status.reblog ? status.reblog : status,
originalStatusId: (({ riginalStatus) }) => originalStatus.id,
statusId: (({ tatus) }) => status.id,
notificationId: (({ otification) }) => notification && notification.id,
```

This is `svelte-upgrade@1.0.15`.

Apologies for not having a reduced repro, but it seems this may be related to the sheer length of the component, because it seems whenever I remove something (the `<style>`, parts of the `<script>`, etc.), then the repro goes away.

**Comment by Rich-Harris** [comment]
fixed in 1.0.16 — thanks
